### PR TITLE
Team Label Icon Element

### PR DESCRIPTION
**Pull request by alexpyoung**
## Information
- **Opened:** 10/31/15
## Requirements
- [[EPIC] Team Priorities/Labels](https://trello.com/c/MOTPIDqo)
## Description of Changes
- Creating initial component
## Issues
- [ ] https://github.com/krossoverintelligence/intelligence-web/issues/292

[Review on Reviewable](https://reviewable.io/reviews/krossoverintelligence/krossover-team-label-icon/1)

### CODE REVIEW

**Comment by d640k** [comment]
Reviewed 6 of 6 files at r1.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

<sup>**[src/controller.js, line 8 \[r1\]](https://reviewable.io:443/reviews/krossoverintelligence/krossover-team-label-icon/1#-K1zNmvi8vesuHR863Ss)** ([raw file](https://github.com/krossoverintelligence/krossover-team-label-icon/blob/b3d5fed68d75e9228766f74b2e8cf720913981bf/src/controller.js#L8)):</sup>
Are you going to use this for something in the future? If we're not using it now, do we need to add this file?


---

<sup>**[src/directive.js, line 4 \[r1\]](https://reviewable.io:443/reviews/krossoverintelligence/krossover-team-label-icon/1#-K1zNMg46o_qVlCFyx0o)** ([raw file](https://github.com/krossoverintelligence/krossover-team-label-icon/blob/b3d5fed68d75e9228766f74b2e8cf720913981bf/src/directive.js#L4)):</sup>
Same as [this](https://reviewable.io/reviews/krossoverintelligence/krossover-priority-select/1#-) pull request comment.


---

<sup>**[src/index.js, line 5 \[r1\]](https://reviewable.io:443/reviews/krossoverintelligence/krossover-team-label-icon/1#-K1zNFfCZOiLjVCWmDHQ)** ([raw file](https://github.com/krossoverintelligence/krossover-team-label-icon/blob/b3d5fed68d75e9228766f74b2e8cf720913981bf/src/index.js#L5)):</sup>
Same as [this](https://reviewable.io/reviews/krossoverintelligence/krossover-priority-select/1#-) pull request comment.


---

<sup>**[src/template.html.js, line 6 \[r1\]](https://reviewable.io:443/reviews/krossoverintelligence/krossover-team-label-icon/1#-K1zN87qSAzli1Qub-bN)** ([raw file](https://github.com/krossoverintelligence/krossover-team-label-icon/blob/b3d5fed68d75e9228766f74b2e8cf720913981bf/src/template.html.js#L6)):</sup>
Do we need the wrapping ```div``` if this is an element directive?


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/krossoverintelligence/krossover-team-label-icon/1)

**Comment by alexpyoung** [comment]
Review status: 3 of 5 files reviewed at latest revision, 4 unresolved discussions, all commit checks successful.

---

<sup>**[src/directive.js, line 4 \[r1\]](https://reviewable.io:443/reviews/krossoverintelligence/krossover-team-label-icon/1#-K1zNMg46o_qVlCFyx0o)** ([raw file](https://github.com/krossoverintelligence/krossover-team-label-icon/blob/b3d5fed68d75e9228766f74b2e8cf720913981bf/src/directive.js#L4)):</sup>
Done.


---

<sup>**[src/index.js, line 5 \[r1\]](https://reviewable.io:443/reviews/krossoverintelligence/krossover-team-label-icon/1#-K1zNFfCZOiLjVCWmDHQ)** ([raw file](https://github.com/krossoverintelligence/krossover-team-label-icon/blob/b3d5fed68d75e9228766f74b2e8cf720913981bf/src/index.js#L5)):</sup>
Done.


---

<sup>**[src/template.html.js, line 6 \[r1\]](https://reviewable.io:443/reviews/krossoverintelligence/krossover-team-label-icon/1#-K1zN87qSAzli1Qub-bN)** ([raw file](https://github.com/krossoverintelligence/krossover-team-label-icon/blob/b3d5fed68d75e9228766f74b2e8cf720913981bf/src/template.html.js#L6)):</sup>
I suppose if `replace` is deprecated then no. https://docs.angularjs.org/error/$compile/tplrt


---

<sup>**[src/controller.js, line 8 \[r1\]](https://reviewable.io:443/reviews/krossoverintelligence/krossover-team-label-icon/1#-K1zNmvi8vesuHR863Ss)** ([raw file](https://github.com/krossoverintelligence/krossover-team-label-icon/blob/b3d5fed68d75e9228766f74b2e8cf720913981bf/src/controller.js#L8)):</sup>
Done.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/krossoverintelligence/krossover-team-label-icon/1)

**Comment by d640k** [comment]
Reviewed 2 of 4 files at r2, 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/krossoverintelligence/krossover-team-label-icon/1)

**Comment by d640k** [comment]
:thumbsup: 6c51a3b


---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/krossoverintelligence/krossover-team-label-icon/1)

**Pull request closed without merging**
